sudo: required

services:
  - docker

language: java
jdk: openjdk11

before_install:
  - mvn fmt:check
  - docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";

script: travis_wait mvn verify jacoco:report

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
    docker push "eu.gcr.io/census-rm-ci/rm/census-rm-case-api";
    fi
  - if [ "$TRAVIS_BRANCH" == "model-update" ] ; then
    docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
    docker tag "eu.gcr.io/census-rm-ci/rm/census-rm-case-api" "eu.gcr.io/census-rm-ci/rm/census-rm-case-api:ade_test";
    docker push "eu.gcr.io/census-rm-ci/rm/census-rm-case-api:ade_test";
    fi

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master
    - model-update
