server:
  port: 8161

info:
  app:
    name: Case API
    version: 1.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres?readOnly=true
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximumPoolSize: 50
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: casev2
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

logging:
  level:
    ROOT: INFO

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  metrics:
    export:
      stackdriver:
        project-id: dummy-project-id
        enabled: false
        step: 15s

uacservice:
  connection:
    scheme: http
    host: localhost
    port: 8164

queueconfig:
  uac-qid-created-exchange: uac-qid-created-exchange
  uac-qid-created-queue: case.uac-qid-created
  events-exchange: events
  fulfilment-event-routing-key: event.fulfilment.request