package uk.gov.ons.census.caseapisvc.model.dto;

public enum EventTypeDTO {
  NEW_CASE,
  RECEIPT,
  REFUSAL,
  INVALID_CASE,
  EQ_LAUNCH,
  RESPONDENT_AUTHENTICATED,
  PRINT_FULFILMENT,
  EXPORT_FILE,
  DEACTIVATE_UAC,
  UPDATE_SAMPLE,
  UPDATE_SAMPLE_SENSITIVE,
  SMS_FULFILMENT,
  ACTION_RULE_SMS_REQUEST,
  EMAIL_FULFILMENT,
  ACTION_RULE_EMAIL_REQUEST,
  ACTION_RULE_SMS_CONFIRMATION,
  ACTION_RULE_EMAIL_CONFIRMATION,
  ERASE_DATA
}
